name: "Build macOS Universal"

on:
  workflow_dispatch:

jobs:
  build_macos_universal:
    runs-on: macos-12
    steps:
    - name: Setup
      run: |
        brew install cmake ninja
        brew uninstall postgresql@14 # not Universal
    - name: Download and unpack
      run: |
        QT_URL="https://download.qt.io/official_releases/qt/5.15/5.15.10/single/qt-everywhere-opensource-src-5.15.10.tar.xz"
        wget -q "${QT_URL}" -O - | tar xJvf -
    - name: Configure
      run: |
        mkdir build
        cd build
        ../qt-everywhere-src-5.15.10/configure -prefix ../install -opensource -confirm-license -release -no-debug-and-release \
            -nomake examples -nomake tests \
            -skip qt3d \
            -skip qtcharts \
            -skip qtdatavis3d \
            -skip qtlocation \
            -skip qtquick3d \
            -skip qtspeech \
            -skip qtvirtualkeyboard \
            -skip qtwebengine \
            QMAKE_APPLE_DEVICE_ARCHS="x86_64 arm64"
    - name: Build
      working-directory: ./build
      run: |
        echo "Note: using $((`sysctl -n hw.ncpu`+1)) parallel jobs"
        make -j$((`sysctl -n hw.ncpu`+1))
    - name: Install
      working-directory: ./build
      run: |
        make install -j1
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: "Qt 5.15.10 for macOS"
        path: ./install/
