name: "Qt 6.2.9 - Windows - amd64"

on:
  workflow_dispatch:

jobs:
  build_qt:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: |
          choco install -y cmake ninja wget 7zip
      - name: Download and unpack source
        shell: bash
        working-directory: D:\a
        run: |
          set -o pipefail
          QT_URL="https://download.qt.io/archive/qt/6.2/6.2.9/single/qt-everywhere-opensource-src-6.2.9.tar.xz"
          wget -q "${QT_URL}" -O - | tar xJvf -
      - name: Configure
        shell: cmd
        working-directory: D:\a
        run: |
          mkdir build
          cd build
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64
          ..\qt-everywhere-src-6.2.9\configure ^
            -prefix D:\a\install ^
            -release ^
            -nomake examples ^
            -submodules qt5compat,qtdeclarative,qtimageformats,qtnetworkauth,qtscxml,qtsvg,qttools,qttranslations,qtxmlpatterns
      - name: Build
        shell: cmd
        working-directory: D:\a\build
        env:
          NINJA_STATUS: "[%f/%t (%c/s avg %o/s); ETA: %W (%P)]   "
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64
          cmake --build . --parallel
      - name: Install
        shell: cmd
        working-directory: D:\a\build
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64
          cmake --install .
      - name: Download pre-built opengl32sw.dll
        shell: bash
        working-directory: D:\a\install\bin
        run: |
          OPENGL32SW_URL="https://download.qt.io/development_releases/prebuilt/llvmpipe/windows/opengl32sw-64-mesa_11_2_2-signed.7z"
          wget -q "${OPENGL32SW_URL}" -O /d/a/opengl32sw.7z
          7z x /d/a/opengl32sw.7z
      - name: Package
        working-directory: D:\a\install
        run: |
          7z a -tzip "../Qt-6.2.9-Windows-amd64.zip" .
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: "Qt-6.2.9-Windows-amd64"
          path: "D:/a/Qt-6.2.9-Windows-amd64.zip"
