name: "Create release"

on:
  workflow_dispatch:
    inputs:
      run-ids:
        description: "Space-separated run IDs of builds to include in the release"
        required: true
        default: ""

permissions:
  actions: read
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_IDS: ${{ github.event.inputs.run-ids }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          mkdir downloads
          cd downloads
          for run_id in $RUN_IDS; do
            echo "Downloading artifacts from run $run_id"
            gh run download $run_id --repo $GITHUB_REPOSITORY
          done
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            downloads/**/*
          name: "MuseScore Qt Build ${{ github.run_id }}"
          tag_name: "v${{ github.run_id }}"
          fail_on_unmatched_files: true
